# How to load dataset with smiles encoding 



In [2]:
from orquestra.drug.drug.discovery. import Smiles, Selfies,MolecularEncoding


In [7]:
selfies = Selfies.from_smiles_csv(
    "/Users/mohamad/workspace/repos/orquestra-drug-discovery/notebook/data/KRAS_G12D_inhibitors.csv"
)


Loading Selfies From CSV: 100%|██████████| 453/453 [00:00<00:00, 738.56it/s]


In [10]:
selfies.as_dataset()

# How to validate and compute rewards for list of molucule

In [11]:
from orquestra.drug.drug.validator import  ConditionFilters
from orquestra.drug.drug.validator import GeneralFilter, PainFilter, WehiMCFilter,SybaFilter
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("/Users/mohamad/workspace/repos/orquestra-drug-discovery/notebook/data/KRAS_G12D_inhibitors.csv")
smi = df.smiles.to_list()

In [14]:
filter_lists=[PainFilter(),GeneralFilter()]
weight_lists=[5.0,1.1]

In [15]:
filter = ConditionFilters(filter_lists=filter_lists,weight_lists=weight_lists)

In [16]:
results = filter.apply_all(smi)

Filtered 447 / 448. passed=258,frac=0.5758928571428571: 100%|██████████| 448/448 [00:36<00:00, 12.33it/s] 


In [18]:
filter.all_rewards

array([6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 5. ,
       5. , 6.1, 5. , 6.1, 5. , 6.1, 5. , 6.1, 5. , 6.1, 5. , 6.1, 6.1,
       5. , 5. , 6.1, 6.1, 5. , 5. , 6.1, 6.1, 6.1, 6.1, 6.1, 5. , 6.1,
       6.1, 5. , 6.1, 5. , 5. , 5. , 6.1, 6.1, 6.1, 5. , 6.1, 5. , 6.1,
       6.1, 5. , 5. , 6.1, 5. , 6.1, 6.1, 6.1, 5. , 6.1, 5. , 5. , 6.1,
       5. , 5. , 6.1, 5. , 5. , 5. , 6.1, 5. , 5. , 5. , 5. , 6.1, 6.1,
       6.1, 5. , 5. , 5. , 6.1, 6.1, 6.1, 6.1, 5. , 6.1, 6.1, 6.1, 6.1,
       6.1, 5. , 6.1, 5. , 6.1, 5. , 6.1, 6.1, 5. , 5. , 5. , 6.1, 5. ,
       5. , 6.1, 6.1, 5. , 6.1, 6.1, 5. , 5. , 5. , 6.1, 6.1, 6.1, 6.1,
       5. , 5. , 6.1, 6.1, 5. , 6.1, 6.1, 6.1, 6.1, 6.1, 5. , 5. , 6.1,
       6.1, 5. , 6.1, 6.1, 5. , 6.1, 5. , 5. , 6.1, 6.1, 5. , 5. , 6.1,
       5. , 5. , 6.1, 5. , 6.1, 5. , 5. , 5. , 5. , 6.1, 6.1, 6.1, 6.1,
       5. , 6.1, 6.1, 6.1, 5. , 6.1, 5. , 6.1, 5. , 5. , 6.1, 6.1, 6.1,
       5. , 5. , 5. , 6.1, 5. , 5. , 5. , 5. , 5. , 6.1, 6.1, 6.

In [17]:
results

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 0., 0.

In [14]:
filter.all_rewards

array([6.1, 5. , 5. , 6.1, 6.1, 6.1, 6.1, 5. , 5. , 6.1, 6.1, 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 5. , 6.1, 6.1, 6.1, 5. , 5. , 5. , 5. , 6.1,
       5. , 6.1, 6.1, 6.1, 6.1, 6.1, 5. , 5. , 6.1, 5. , 6.1, 5. , 5. ,
       5. , 6.1, 5. , 6.1, 5. , 5. , 6.1, 5. , 6.1, 6.1, 5. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 5. , 5. , 6.1, 5. , 5. , 6.1, 5. , 6.1, 5. ,
       6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 5. , 6.1, 5. , 6.1, 5. , 5. ,
       6.1, 5. , 6.1, 6.1, 5. , 5. , 5. , 5. , 6.1, 5. , 5. , 6.1, 6.1,
       5. , 5. , 6.1, 6.1, 6.1, 6.1, 6.1, 5. , 5. , 5. , 5. , 5. , 5. ,
       5. , 5. , 6.1, 5. , 6.1, 6.1, 5. , 5. , 5. , 5. , 6.1, 6.1, 6.1,
       6.1, 5. , 5. , 5. , 5. , 5. , 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 5. ,
       5. , 6.1, 5. , 6.1, 6.1, 5. , 5. , 6.1, 6.1, 6.1, 6.1, 6.1, 5. ,
       5. , 6.1, 5. , 5. , 5. , 5. , 6.1, 5. , 5. , 6.1, 5. , 6.1, 6.1,
       5. , 5. , 6.1, 6.1, 6.1, 6.1, 6.1, 5. , 6.1, 6.1, 6.1, 5. , 6.1,
       5. , 6.1, 5. , 6.1, 6.1, 6.1, 5. , 5. , 6.1, 6.1, 6.1, 6.